### ISSUE TITLE
TextureAtlass async loading issue

### ISSUE THREAD

**Issue by toxa-ak88** [libktx/ktx#88] opened 2017-06-21 22:50 UTC
- [ ] Convert `TextAssetLoader` to `AsynchronousAssetLoader`.
- [ ] Handle `SynchronousAssetLoader` instances on the main rendering thread.

---

I get an exception during **TextureAtlas** async loading:

> Exception in thread "LWJGL Application" ktx.async.assets.AssetStorageException: Unable to load asset at: textures/preloader/preloader.atlas
> 	at ktx.async.assets.AssetStorage$load$1.doResume(assets.kt:119)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:60)
> 	at ktx.async.KtxContinuation$resumeWithException$1.run(async.kt:172)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:259)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:210)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
> Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
> 	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
> 	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:651)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glBindTexture(LwjglGL20.java:93)
> 	at com.badlogic.gdx.graphics.GLTexture.bind(GLTexture.java:66)
> 	at com.badlogic.gdx.graphics.GLTexture.setFilter(GLTexture.java:162)
> 	at com.badlogic.gdx.graphics.g2d.TextureAtlas.load(TextureAtlas.java:249)
> 	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:236)
> 	at com.badlogic.gdx.assets.loaders.TextureAtlasLoader.load(TextureAtlasLoader.java:48)
> 	at com.badlogic.gdx.assets.loaders.TextureAtlasLoader.load(TextureAtlasLoader.java:34)
> 	at ktx.async.assets.LoadersKt.load(loaders.kt:151)
> 	at ktx.async.assets.AssetStorage$loadWithSynchronousLoader$1.invoke(assets.kt:177)
> 	at ktx.async.KtxAsync$asynchronous$$inlined$suspendCancellableCoroutine$lambda$1.call(async.kt:99)
> 	at ktx.async.KtxAsync$asynchronous$$inlined$suspendCancellableCoroutine$lambda$1.call(async.kt:25)
> 	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> AL lib: (EE) alc_cleanup: 1 device not closed

Here is the code to reproduce it:
```
override fun create() {
        enableKtxCoroutines(asynchronousExecutorConcurrencyLevel = 1)

        val storage = AssetStorage ()

        ktxAsync {
            storage.apply {
                val texture = load<Texture>("badlogic.jpg")
                println(texture)
                val atlas = load<TextureAtlas>("textures/preloader/preloader.atlas")
                println(atlas)
            }
        }
    }
```
please note that Texture loaded correctly, but TextureAtlas crushes the app.

When I use **AssetManager** both loaded well.
It reproduced on

> kotlinVersion = '1.1.2-5'
>         kotlinCoroutinesVersion = '0.16'
>         ktxVersion = '1.9.6-b5'

I will be pleased with any suggestion.
Thanks in advance.

**Comment by czyzby** [comment] 2017-06-21 23:17
OK, I know what's the issue. `AssetManager` code was highly convoluted and when I saw some kind of scheduling tasks, I assumed that `SynchronousLoaders` are also handled by a separate thread, but it seems that the loading tasks are actually executed on the main thread. The unit tests have not revealed this, as the OpenGL context is mocked during testing. That's an easy fix, I'll look into it soon and release `1.9.6-b6`.

**Comment by czyzby** [comment] 2017-06-21 23:42
Yeah, I was able to reproduce the issue before the changes and it seems to be fixed after the last 2 commits. Snapshot is being released as we speak - as a quick fix, you can use `1.9.6-SNAPSHOT` version for now. This is a pretty serious issue, so I'm going to upload the next beta release soon.

**Closed by czyzby** 2017-06-21 23:42 UTC
Labels: assets, async, bug

**Comment by toxa-ak88** [comment] 2017-06-21 23:52
Great. thanks. You absolutely smashed it.

**Comment by czyzby** [comment] 2017-06-21 23:59
It's a bit embarrassing, really, cause I've tested `AssetStorage` in actual applications, but it seems I've never used atlases then. `AssetManager` was a hell to rewrite (or should I say - a _callback hell_) using coroutines. Should have tested it more thoroughly.

Anyway, I've uploaded `1.9.6-b6` to Maven Central - it should be already available.

**Comment by toxa-ak88** [comment] 2017-06-22 08:07
Great job.
