### ISSUE TITLE
LibGdx main dispatcher

### ISSUE THREAD

**Issue by jcornaz** [libktx/ktx#169] opened 2018-12-04 09:28 UTC
Hi,

In my humble opinion, the `async` module misses the only feature I'd expect him to provide: A dispatcher for the LibGDX main thread.

Here is how to write it:

```kotlin
public val Dispatchers.LibGdx: CoroutineDispatcher get() = LibGdxDispatcher

private object LibGdxDispatcher : MainCoroutineDispatcher() {

  @ExperimentalCoroutinesApi
  override val immediate = object : MainCoroutineDispatcher() {
    @ExperimentalCoroutinesApi
    override val immediate: MainCoroutineDispatcher get() = this

    override fun dispatch(context: CoroutineContext, block: Runnable) = block.run()
  }

  override fun dispatch(context: CoroutineContext, block: Runnable) = Gdx.app.postRunnable(block)
}
```

And how to use it:

```kotlin
fun CoroutineScope.startLibGdxCoroutine() = launch(Dispatchers.Main) { // <-- We can use any coroutine builder

  // Here we are on a frame update by the LibGDX thread.
  
  delay(1000) // <-- Call any suspending function (no need to use the `KtxAsync.delay`)
 
  // Here we are back on a frame update by the LibGDX thread

  withContext(Dispatchers.Main) {
    // It is not needed in this case, but one may use `withContext` to perform an operation on a frame update of the LibGDX thread
  }
}
```

**Comment by czyzby** [comment] 2018-12-04 13:19
Already on this. New coroutines API requires a complete redesign of the `ktx-async` module. I cannot give you any time estimates, but just wanted you to know I'm getting close to the next release.

There will be 2 dispatchers based on LibGDX API: for the rendering thread (using `Gdx.app.postRunnable`) and wrapping `AsyncExecutor` (using `executor.submit`).

**Comment by jcornaz** [comment] 2018-12-04 14:02
Thank you very much for your work. Game programming is very pleasant with Kotlin and KTX ;-)

**Comment by czyzby** [comment] 2018-12-04 22:08
I'm going to close this as a duplicate of #154, but I'm still working on this. Recent weeks were pretty busy for me, but now I have a bit more free time - I want to finish the `ktx-async` refactor and immutable vectors merge by the end of the week.

**Closed by czyzby** 2018-12-04 22:08 UTC
Labels: async
